server:
  port: 8000

spring:
  application:
    name: my-zuul-service

zuul:
  routes:
    first-service:
      path: /first-service/** # 이 경로로 들어오는 요청은 아래 url로 보냄
      url: http://localhost:8081
    second-service:
      path: /second-service/**
      url: http://localhost:8082