version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zoo
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.7.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "quickstart-events:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
