server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\\Users\\ygaso\\workspace\\config-local
        git:
          uri: file:///C:\\Users\\ygaso\\workspace\\config-local